baseURL = "/blog"
publishDir = "site/blog"
contentDir = "blogposts"
languageCode = "en-us"
uglyURLs = true
copyright = "(c) Light Code Labs. All rights reserved."
title = "The Caddy Blog"

[blackfriday]
extensionsmask = [ "autolink" ]
fractions = false
smartypants = false

[taxonomies]
# none
